# Generated by Django 3.1.4 on 2021-01-10 04:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 10, 4, 33, 46, 593422, tzinfo=utc), verbose_name='date published'),
        ),
    ]
