# Generated by Django 3.1.4 on 2021-01-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_auto_20210110_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='history',
            name='date',
            field=models.TextField(default='01-11'),
        ),
        migrations.AddField(
            model_name='history',
            name='time',
            field=models.TextField(default='12:55'),
        ),
        migrations.AlterField(
            model_name='history',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
