# Generated by Django 3.1.4 on 2021-01-10 06:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_history_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 10, 6, 52, 23, 260251, tzinfo=utc), verbose_name='date published'),
        ),
    ]
